/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */

#include <panic.h>
#include <string.h>
#include "sink_gatt_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Primary Service fee7 */
    0x0002, 0xe7fe,
    /* 0003: Characteristic Declaration fec7 */
    0x3005, 0x0804, 0x00c7, 0xfe00,
    /* 0004: . */
    0xd401, 0x0000,
    /* 0005: Characteristic Declaration fec8 */
    0x3005, 0x2006, 0x00c8, 0xfe00,
    /* 0006: . */
    0xd401, 0x0000,
    /* 0007: Client Characteristic Configuration */
    0x6c00,
    /* 0008: Characteristic Declaration fec9 */
    0x3005, 0x0209, 0x00c9, 0xfe00,
    /* 0009: . */
    0xd401, 0x0000,
    /* 000a: Primary Service 1800 */
    0x0002, 0x0018,
    /* 000b: Characteristic Declaration 2a00 */
    0x3005, 0x020c, 0x0000, 0x2a00,
    /* 000c:  */
    0xd400,
    /* 000d: Characteristic Declaration 2a01 */
    0x3005, 0x020e, 0x0001, 0x2a00,
    /* 000e:  */
    0xd400,
};

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

/* End-of-File */
