/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */

#include <panic.h>
#include <string.h>
#include "sink_gatt_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0003: Characteristic Declaration 2a19 */
    0x3005, 0x1204, 0x0019, 0x2a00,
    /* 0004: . */
    0xd401, 0x0000,
    /* 0005: Client Characteristic Configuration */
    0x6c00,
    /* 0006: Primary Service 180d */
    0x0002, 0x0d18,
    /* 0007: Characteristic Declaration 2a37 */
    0x3005, 0x1208, 0x0037, 0x2a00,
    /* 0008: . */
    0xd401, 0x0000,
    /* 0009: Client Characteristic Configuration */
    0x6c00,
    /* 000a: Primary Service 1900 */
    0x0002, 0x0019,
    /* 000b: Characteristic Declaration 2b01 */
    0x3005, 0x0a0c, 0x0001, 0x2b00,
    /* 000c: . */
    0xd401, 0x0000,
    /* 000d: Characteristic Declaration 2b02 */
    0x3005, 0x0a0e, 0x0002, 0x2b00,
    /* 000e: . */
    0xd401, 0x0000,
    /* 000f: Characteristic Declaration 2b10 */
    0x3005, 0x1010, 0x0010, 0x2b00,
    /* 0010: . */
    0xd401, 0x0000,
    /* 0011: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0012: Characteristic Declaration 2a00 */
    0x3005, 0x0213, 0x0000, 0x2a00,
    /* 0013:  */
    0xd400,
    /* 0014: Characteristic Declaration 2a01 */
    0x3005, 0x0215, 0x0001, 0x2a00,
    /* 0015:  */
    0xd400,
};

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

/* End-of-File */
