/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */
#ifndef __SINK_GATT_DB_H
#define __SINK_GATT_DB_H

#include <csrtypes.h>

#define HANDLE_GATT_SERVICE             (0x0001)
#define HANDLE_WeChat                   (0x0002)
#define HANDLE_WRITE_CHARACTERISTIC     (0x0004)
#define HANDLE_INDICATE_CHARACTERISTIC  (0x0006)
#define HANDLE_WECHAR_CLIENT_CONFIG     (0x0007)
#define HANDLE_READ_CHARACTERISTIC      (0x0009)
#define HANDLE_GAP_SERVICE              (0x000a)
#define HANDLE_DEVICE_NAME              (0x000c)
#define HANDLE_DEVICE_APPEARANCE        (0x000e)

uint16 *GattGetDatabase(uint16 *len);

#endif

/* End-of-File */
